server:
  port: 8581
  servlet.context-path: /client-profile
spring:
  application.name: client-profile
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/loadbalancing
    username: root
    password: 123456@A
  jpa:
    show-sql: true
  kafka:
#    bootstrapServers: ${kafka_server_url:http://host.docker.internal:9092}
    producer:
      bootstrap-servers: ${kafka_server_url:http://host.docker.internal:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_server_url:http://host.docker.internal:8761}/eureka/
  instance:
    statusPageUrl: http://localhost:8581/client-profile/actuator/health
