version: "3"
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0.26
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456@A'
      MYSQL_USER: 'admin'
      MYSQL_PASS: '123456@A'
    volumes:
      - /Users/lequoctruong/Documents/docker-volume/mysql:/var/lib/mysql